var questions = [{
    "question": "what does html refers?",
    "option1":"content",
    "option2":"style",
    "option3":"browser",
    "option4":"none",
    "answer":"1",
}, {
    "question": "what does CSS refers?",
    "option1":"content",
    "option2":"style",
    "option3":"browser",
    "option4":"none",
    "answer":"2",
    
},{
    "question": "Which pseudo class is used for providing mouse over property?",
    "option1":":link",
    "option2":":hover",
    "option3":":click",
    "option4":":active",
    "answer":"2",
},{
    "question": "Name the property we use to change the background color",
    "option1":"color",
    "option2":" background-color ",
    "option3":"display-color",
    "option4":"none",
    "answer":"2",


},{
    "question": "What is the tag we use to add columns to tables",
    "option1":"<td>",
    "option2":" <colspan>.",
    "option3":"<tr>.",
    "option4":"<th>",
    "answer":"1",
},{
    "question": " How many parents does the root node have",
    "option1":"Many.",
    "option2":"0",
    "option3":"1.",
    "option4":"2",
    "answer":"0",
},{
    "question": "which function is used the prompt user to enter Data?",
    "option1":"console.log()",
    "option2":" alert() ",
    "option3":"windows. alert() ",
    "option4":"none",
    "answer":"2",
},{
    "question": "The <img> tag uses which of the following attributes?",
    "option1":"href",
    "option2":"src",
    "option3":"both",
    "option4":"none",
    "answer":"2",
},{
    "question": "Which type of list uses bullets?",
    "option1":"<ol>",
    "option2":" <ul>",
    "option3":"<li>",
    "option4":"none",
    "answer":"2",
},{
    "question": "Which class provides a responsive fixed width container?",
    "option1":".container-fluid",
    "option2":".container",
    "option3":".container-fixed",
    "option4":"none",
    "answer":"2",
}];